- hosts: tomcat
  become: true
  tasks:
    - name: Deploy in tomcat
      copy:
        src: /var/lib/jenkins/workspace/demo app new/target/java-web-app-2.0.0.war
        dest: /home/ubuntu/apache-tomcat-9.0.69/webapps
