---
- hosts: tomcat
  become: true
  tasks:
    - name: Deploy in tomcat
      copy:
        src: /var/lib/jenkins/workspace/demoapplication/target/java-web-app-2.0.0.war
        dest: /home/ubuntu/tomcat/webapps
