---
- hosts: tomcat
  become: true
  tasks:
    - name: Download war file
      maven_artifact:
        group_id: com.mt
        artifact_id: java-web-app
        extension: war
        version: 2.0.0
        repository_url: http://54.82.86.48:8081/repository/test-release/
        username: admin
        password: admin123
        dest: /tmp/java-web-app-2.0.0.war
        mode: "0644"
    - name: Copy the war file
      copy:
        src: /tmp/hello-world-war-1.0.0.war
        dest: /opt/apache-tomcat-9.0.71/webapps
        remote_src: yes
