apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ak-deployment
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: my-java-app
        image: account1996/java:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-svc
  namespace: test-ns
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
