#---- Replicaset Manefests File -------

apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: pythonrs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonrs
    matchExpressions: # Set Based
    - key: app
      operators: not in 
      values: 
      - pythonapp
      - python
  template: #Pod Template
    metadata:
      name: pythonappod
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: dockerhandson/python-app:1
        ports:
        - containerPort: 4000

#------ With Service ( Node Port)-----------

apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 6000
    nodeport: 31666


<html>
<head>
  <title> This is app view to show it's working</title>
</head>

<body>
  <h1> this is body check </h1>
</body>
</html>
